import React from 'react';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import '@testing-library/jest-dom';
import { BrowserRouter } from 'react-router-dom';
import PositionBoard from '../PositionBoard';
import * as positionService from '../../services/positionService';

// Mock the position service
jest.mock('../../services/positionService');
const mockedPositionService = positionService as jest.Mocked<typeof positionService>;

// Mock data
const mockPositionData = {
  positionName: 'Senior Frontend Developer',
  interviewFlow: {
    id: 1,
    description: 'Frontend interview process',
    interviewSteps: [
      { id: 1, name: 'Initial Screening', orderIndex: 1 },
      { id: 2, name: 'Technical Interview', orderIndex: 2 },
      { id: 3, name: 'Manager Interview', orderIndex: 3 }
    ]
  }
};

const mockCandidates = [
  {
    id: 1,
    applicationId: 101,
    fullName: 'Ana García',
    currentInterviewStep: 'Initial Screening',
    currentInterviewStepId: 1,
    averageScore: 4.5
  },
  {
    id: 2,
    applicationId: 102,
    fullName: 'Carlos Rodríguez',
    currentInterviewStep: 'Technical Interview',
    currentInterviewStepId: 2,
    averageScore: 3.8
  }
];

const renderWithRouter = (component: React.ReactElement) => {
  return render(
    <BrowserRouter>
      {component}
    </BrowserRouter>
  );
};

// Mock useParams to return position ID
jest.mock('react-router-dom', () => ({
  ...jest.requireActual('react-router-dom'),
  useParams: () => ({ id: '1' }),
  useNavigate: () => jest.fn()
}));

describe('Accessibility Features', () => {
  beforeEach(() => {
    mockedPositionService.getInterviewFlow.mockResolvedValue(mockPositionData);
    mockedPositionService.getCandidatesByPosition.mockResolvedValue(mockCandidates);
    mockedPositionService.updateCandidateStageOptimistic.mockResolvedValue({
      message: 'Success',
      data: { id: 101, positionId: 1, candidateId: 1, currentInterviewStep: 2 }
    });
  });

  afterEach(() => {
    jest.clearAllMocks();
  });

  describe('ARIA Labels and Descriptions', () => {
    test('should have proper ARIA labels for main components', async () => {
      renderWithRouter(<PositionBoard />);
      
      await waitFor(() => {
        expect(screen.getByText('Senior Frontend Developer')).toBeInTheDocument();
      });

      // Main container should have proper ARIA label
      const mainContainer = screen.getByRole('main');
      expect(mainContainer).toHaveAttribute('aria-label', 'Position board for candidate management');

      // Each column should have proper ARIA labels
      const columns = screen.getAllByRole('region');
      expect(columns[0]).toHaveAttribute('aria-label', 'Initial Screening - 1 candidates');
      expect(columns[1]).toHaveAttribute('aria-label', 'Technical Interview - 1 candidates');
      expect(columns[2]).toHaveAttribute('aria-label', 'Manager Interview - 0 candidates');
    });

    test('should have descriptive ARIA labels for candidate cards', async () => {
      renderWithRouter(<PositionBoard />);
      
      await waitFor(() => {
        expect(screen.getByText('Ana García')).toBeInTheDocument();
      });

      const anaCard = screen.getByTestId('candidate-card-1');
      expect(anaCard).toHaveAttribute('aria-label', 'Candidate Ana García, Score 4.5 out of 5, Current stage: Initial Screening');
      
      const carlosCard = screen.getByTestId('candidate-card-2');
      expect(carlosCard).toHaveAttribute('aria-label', 'Candidate Carlos Rodríguez, Score 3.8 out of 5, Current stage: Technical Interview');
    });

    test('should announce drag and drop instructions', async () => {
      renderWithRouter(<PositionBoard />);
      
      await waitFor(() => {
        expect(screen.getByText('Ana García')).toBeInTheDocument();
      });

      // Check for drag and drop instructions for screen readers (generated by @dnd-kit)
      const instructionsContainer = document.querySelector('#DndDescribedBy-0, [id*="DndDescribedBy"]');
      expect(instructionsContainer).toBeInTheDocument();
      expect(instructionsContainer).toHaveStyle('display: none'); // Hidden but available to screen readers
    });

    test('should have live region for dynamic updates', async () => {
      renderWithRouter(<PositionBoard />);
      
      await waitFor(() => {
        expect(screen.getByText('Ana García')).toBeInTheDocument();
      });

      // Check for ARIA live region (our custom one)
      const liveRegion = screen.getByTestId('live-region');
      expect(liveRegion).toHaveAttribute('role', 'status');
      expect(liveRegion).toHaveAttribute('aria-live', 'assertive');
      expect(liveRegion).toHaveAttribute('aria-atomic', 'true');
    });
  });

  describe('Keyboard Navigation', () => {
    test('should support keyboard navigation between candidate cards', async () => {
      renderWithRouter(<PositionBoard />);
      
      await waitFor(() => {
        expect(screen.getByText('Ana García')).toBeInTheDocument();
      });

      const anaCard = screen.getByTestId('candidate-card-1');
      const carlosCard = screen.getByTestId('candidate-card-2');

      // Both cards should be focusable
      expect(anaCard).toHaveAttribute('tabindex', '0');
      expect(carlosCard).toHaveAttribute('tabindex', '0');

      // Focus first card
      anaCard.focus();
      expect(anaCard).toHaveFocus();

      // Tab to next card
      fireEvent.keyDown(anaCard, { key: 'Tab' });
      // Note: Tab navigation testing is complex, we're mainly checking tabindex exists
    });

    test('should handle Enter and Space key activation', async () => {
      renderWithRouter(<PositionBoard />);
      
      await waitFor(() => {
        expect(screen.getByText('Ana García')).toBeInTheDocument();
      });

      const anaCard = screen.getByTestId('candidate-card-1');
      
      // Test Enter key
      fireEvent.keyDown(anaCard, { key: 'Enter' });
      // Should not cause errors (handled by component)

      // Test Space key (used by drag and drop)
      fireEvent.keyDown(anaCard, { key: ' ' });
      // Should not cause errors (handled by dnd-kit)
    });

    test('should support Escape key to cancel drag operations', async () => {
      renderWithRouter(<PositionBoard />);
      
      await waitFor(() => {
        expect(screen.getByText('Ana García')).toBeInTheDocument();
      });

      const anaCard = screen.getByTestId('candidate-card-1');
      
      // Start drag with Space, then cancel with Escape
      fireEvent.keyDown(anaCard, { key: ' ' });
      fireEvent.keyDown(document, { key: 'Escape' });
      
      // Should not cause errors and should cancel any ongoing drag
      expect(anaCard).toBeInTheDocument();
    });

    test('should support arrow key navigation during drag', async () => {
      renderWithRouter(<PositionBoard />);
      
      await waitFor(() => {
        expect(screen.getByText('Ana García')).toBeInTheDocument();
      });

      const anaCard = screen.getByTestId('candidate-card-1');
      
      // Test arrow key navigation (handled by dnd-kit)
      fireEvent.keyDown(anaCard, { key: 'ArrowRight' });
      fireEvent.keyDown(anaCard, { key: 'ArrowLeft' });
      fireEvent.keyDown(anaCard, { key: 'ArrowDown' });
      fireEvent.keyDown(anaCard, { key: 'ArrowUp' });
      
      // Should not cause errors
      expect(anaCard).toBeInTheDocument();
    });
  });

  describe('Focus Management', () => {
    test('should maintain focus on back button', async () => {
      renderWithRouter(<PositionBoard />);
      
      await waitFor(() => {
        expect(screen.getByText('Senior Frontend Developer')).toBeInTheDocument();
      });

      const backButton = screen.getByTestId('back-button');
      expect(backButton).toBeInTheDocument();
      
      // Back button should be focusable
      backButton.focus();
      expect(backButton).toHaveFocus();
    });

    test('should provide focus indicators for interactive elements', async () => {
      renderWithRouter(<PositionBoard />);
      
      await waitFor(() => {
        expect(screen.getByText('Ana García')).toBeInTheDocument();
      });

      const anaCard = screen.getByTestId('candidate-card-1');
      
      // Focus the card and check it receives focus styles
      fireEvent.focus(anaCard);
      expect(anaCard).toHaveFocus();
    });

    test('should trap focus within modals or dialogs', async () => {
      // This test would be relevant if we add modal dialogs in the future
      // For now, we ensure focus management works on the main board
      renderWithRouter(<PositionBoard />);
      
      await waitFor(() => {
        expect(screen.getByText('Ana García')).toBeInTheDocument();
      });

      // Test that focus management doesn't break with multiple interactive elements
      const backButton = screen.getByTestId('back-button');
      const anaCard = screen.getByTestId('candidate-card-1');
      
      expect(backButton).toBeInTheDocument();
      expect(anaCard).toBeInTheDocument();
    });
  });

  describe('Screen Reader Support', () => {
    test('should announce drag state changes', async () => {
      renderWithRouter(<PositionBoard />);
      
      await waitFor(() => {
        expect(screen.getByText('Ana García')).toBeInTheDocument();
      });

      const anaCard = screen.getByTestId('candidate-card-1');
      
      // Card should have proper role description for screen readers
      expect(anaCard).toHaveAttribute('aria-roledescription', 'draggable');
    });

    test('should provide meaningful headings hierarchy', async () => {
      renderWithRouter(<PositionBoard />);
      
      await waitFor(() => {
        expect(screen.getByText('Senior Frontend Developer')).toBeInTheDocument();
      });

      // Main title should be h1
      const mainTitle = screen.getByRole('heading', { level: 1 });
      expect(mainTitle).toHaveTextContent('Senior Frontend Developer');

      // Column titles should be h5 (as per Bootstrap design)
      const columnTitles = screen.getAllByRole('heading', { level: 5 });
      expect(columnTitles).toHaveLength(3);
      expect(columnTitles[0]).toHaveTextContent('Initial Screening');
      expect(columnTitles[1]).toHaveTextContent('Technical Interview');
      expect(columnTitles[2]).toHaveTextContent('Manager Interview');
    });

    test('should announce candidate count changes', async () => {
      renderWithRouter(<PositionBoard />);
      
      await waitFor(() => {
        expect(screen.getByText('Ana García')).toBeInTheDocument();
      });

      // Column headers should include candidate counts
      const initialColumn = screen.getByLabelText('Initial Screening - 1 candidates');
      const technicalColumn = screen.getByLabelText('Technical Interview - 1 candidates');
      const managerColumn = screen.getByLabelText('Manager Interview - 0 candidates');

      expect(initialColumn).toBeInTheDocument();
      expect(technicalColumn).toBeInTheDocument();
      expect(managerColumn).toBeInTheDocument();
    });
  });

  describe('High Contrast and Visual Accessibility', () => {
    test('should have sufficient color contrast for text', async () => {
      renderWithRouter(<PositionBoard />);
      
      await waitFor(() => {
        expect(screen.getByText('Ana García')).toBeInTheDocument();
      });

      // Test that important elements have proper CSS classes for contrast
      const anaCard = screen.getByTestId('candidate-card-1');
      expect(anaCard).toHaveClass('candidate-card');
      
      const mainTitle = screen.getByTestId('position-title');
      expect(mainTitle).toHaveClass('position-board-title');
    });

    test('should support reduced motion preferences', async () => {
      renderWithRouter(<PositionBoard />);
      
      await waitFor(() => {
        expect(screen.getByText('Ana García')).toBeInTheDocument();
      });

      // Components should render without motion-dependent functionality breaking
      const kanbanBoard = screen.getByRole('main');
      expect(kanbanBoard).toBeInTheDocument();
    });

    test('should provide visual focus indicators', async () => {
      renderWithRouter(<PositionBoard />);
      
      await waitFor(() => {
        expect(screen.getByText('Ana García')).toBeInTheDocument();
      });

      const anaCard = screen.getByTestId('candidate-card-1');
      
      // Ensure focusable elements have proper attributes for styling
      expect(anaCard).toHaveAttribute('tabindex', '0');
      expect(anaCard).toHaveAttribute('role', 'button');
    });
  });
});
